eureka:
    client:
        serviceUrl:
            defaultZone: http://ack-center-node1:8761/eureka/,http://ack-center-node2:8766/eureka/
    instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 5
server:
    port: 8762
spring:
    application:
        name: service-helloworld